"""add the order column to the question table

Revision ID: 1be3713ae718
Revises: 70e4e52be2a8
Create Date: 2021-11-10 16:45:01.928554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be3713ae718'
down_revision = '70e4e52be2a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'order')
    # ### end Alembic commands ###
