"""add image column to mood table

Revision ID: 70e4e52be2a8
Revises: cbbf822c6b4f
Create Date: 2021-07-19 14:29:50.400728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e4e52be2a8'
down_revision = 'cbbf822c6b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mood', 'image')
    # ### end Alembic commands ###
