"""add mode column to the question table

Revision ID: 98dd8abb9fc0
Revises: 9ed7191281d6
Create Date: 2021-12-13 17:47:35.124112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98dd8abb9fc0'
down_revision = '9ed7191281d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('mode', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'mode')
    # ### end Alembic commands ###
