"""add a view column to the question table

Revision ID: 9ed7191281d6
Revises: db5c45af24c7
Create Date: 2021-11-30 18:43:29.632482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed7191281d6'
down_revision = 'db5c45af24c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('view', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'view')
    # ### end Alembic commands ###
