"""add a secret column to the answer table

Revision ID: 9f8a01d868b9
Revises: 98dd8abb9fc0
Create Date: 2021-12-20 17:00:04.961506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8a01d868b9'
down_revision = '98dd8abb9fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'secret')
    # ### end Alembic commands ###
