"""initial migration

Revision ID: a294944cfb54
Revises: 
Create Date: 2021-06-14 16:29:19.337508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a294944cfb54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mood'))
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('client_id', name=op.f('uq_user_client_id'))
    )
    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name=op.f('fk_scenario_topic_id_topic')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario'))
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('question_type', sa.Enum('SINGLE_CHOICE', 'MULTI_CHOICE', 'FREE_TEXT', name='questiontypeenum'), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], name=op.f('fk_question_scenario_id_scenario')),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name=op.f('fk_question_topic_id_topic')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question'))
    )
    op.create_table('vision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mood_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mood_id'], ['mood.id'], name=op.f('fk_vision_mood_id_mood')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], name=op.f('fk_vision_scenario_id_scenario')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_vision_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vision'))
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_answer_question_id_question')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_answer_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer'))
    )
    op.create_table('choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_choice_question_id_question')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_choice'))
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ERROR', name='gamestatusenum'), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('vision_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_game_user_id_user')),
    sa.ForeignKeyConstraint(['vision_id'], ['vision.id'], name=op.f('fk_game_vision_id_vision')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game'))
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('unsplash_image_id', sa.String(), nullable=True),
    sa.Column('unsplash_creator_name', sa.String(), nullable=True),
    sa.Column('unsplash_creator_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'GIF', 'VIDEO', 'TEXT', name='mediatypeenum'), nullable=True),
    sa.Column('vision_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vision_id'], ['vision.id'], name=op.f('fk_media_vision_id_vision')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
    )
    op.create_table('answers_choice_table',
    sa.Column('choice_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], name=op.f('fk_answers_choice_table_answer_id_answer')),
    sa.ForeignKeyConstraint(['choice_id'], ['choice.id'], name=op.f('fk_answers_choice_table_choice_id_choice'))
    )
    op.create_table('guess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('mood_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_guess_game_id_game')),
    sa.ForeignKeyConstraint(['mood_id'], ['mood.id'], name=op.f('fk_guess_mood_id_mood')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guess'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guess')
    op.drop_table('answers_choice_table')
    op.drop_table('media')
    op.drop_table('game')
    op.drop_table('choice')
    op.drop_table('answer')
    op.drop_table('vision')
    op.drop_table('question')
    op.drop_table('scenario')
    op.drop_table('user')
    op.drop_table('topic')
    op.drop_table('mood')
    # ### end Alembic commands ###
