"""add page to the question table

Revision ID: c2a8bbbbabc1
Revises: d6aff6a9d3ad
Create Date: 2021-11-19 11:03:25.844130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a8bbbbabc1'
down_revision = 'd6aff6a9d3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('page', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'page')
    # ### end Alembic commands ###
