"""add user client type

Revision ID: cbbf822c6b4f
Revises: a294944cfb54
Create Date: 2021-06-21 18:23:43.202954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbbf822c6b4f'
down_revision = 'a294944cfb54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('client_type', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'client_type')
    # ### end Alembic commands ###
