"""add the order column to the mood table

Revision ID: d6aff6a9d3ad
Revises: 1be3713ae718
Create Date: 2021-11-10 16:55:49.414836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6aff6a9d3ad'
down_revision = '1be3713ae718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mood', 'order')
    # ### end Alembic commands ###
